Allow GET by xdd_uri
DARPA-ASKEM/data-service pull request #159
Opened 2023-01-20 16:56 UTC by fivegrant

2023-01-20 16:58 UTC, marshHawk4 approved these changes
LGTM

2023-01-20 17:08 UTC, mattprintz requested changes

2023-01-20 17:08 UTC, mattprintz commented on tds/routers/external.py
>              publication = session.query(orm.Publication).get(id)
We should be able to do this in one query, and should do so, I think.

2023-01-20 17:08 UTC, mattprintz commented on tds/routers/external.py
> +            )
What is the expected behavior if the payload matches the xdd_uri, but has a different description? In this case, the different description is silently ignored. Is that what we want?

2023-01-24 16:56 UTC, mattprintz approved these changes

2023-01-24 17:13 UTC, merged