Feat/provenance upgrade ql
DARPA-ASKEM/data-service pull request #170
Opened 2023-02-06 20:58 UTC by marshHawk4

2023-02-07 14:28 UTC, fivegrant requested changes
I understand we want to request the nodes and not the edges but I think I'm still a bit confused by what's being returned by the GraphQL. Is it all the related nodes or ones that are a single relationship away? Could we fit some of these provenance queries into the objects themselves (e.g. a `related` field on `Model`)?

2023-02-07 14:28 UTC, fivegrant commented on askem.dbml
> +  description text
We probably want to hold off on changes to `askem.dbml` until we have some kind of migration flow set up. Would it be possible to revert this old dbml + autogen files? Is this change necessary to make GraphQL Provenance work?

2023-02-07 14:28 UTC, fivegrant commented on askem.dbml
> +  description text
cc @mattprintz

2023-02-07 16:27 UTC, marshHawk4 commented
> 

*for what is being returned. So we are returning all connected nodes n(hops) relationships away or until n (limit) number of nodes are found. Basically it will return all nodes of the subgraph. We allow them to filter the search to only return nodes of interest. They can return only one relationship away if they set hops to 1. I am not exposing the ability to return model revision here.

2023-02-08 18:50 UTC, fivegrant requested changes
Ran into an issue with model and publication provenance. Issue has been attached
[test.txt](https://github.com/DARPA-ASKEM/data-service/files/10688950/test.txt)

2023-03-23 20:22 UTC, fivegrant approved these changes

2023-03-23 21:42 UTC, mattprintz approved these changes
Looks good.

2023-03-23 21:48 UTC, merged